### ISSUE TITLE
no registration possible 

### ISSUE THREAD

**Issue by Drifti** [monsieurbiz/Mbiz_InvisibleCaptcha#1]
After installation in Magento 1.9.3.8, filling the website-key and the secret-key and activation in menu for contact-form and registration-form nothing happens when sending the filled customer registration form.
Just the filled letters disapears.

Are there other changes to do for use the extension in these 2 forms (contact page & registration)?

In the description, there is only the contact-form named, but in the menu there is also the registration-form possible to activate.

**Comment by jacquesbh** [comment]
Hi,

Did you follow the README?

You have to update your `phtml` files.

**Comment by Drifti** [comment]
Hi,
I just copied the files in the folders "app" and "js", cleaned the cache, log out, log in.
From your backend menu "invisible ReCaptcha" I filled in the 2 Google codes and activated the module for contact-form and registration form from backend.
Active: Yes

Contacts form: Yes
Replace template: No

Registration form: Yes
Replace template: No

That's all I did.
 
Do you mean the readme part under" You just have to make few changes (only additions):"?
I thought, this step is only necessary for other forms than contact form & registration form, am I right?

If I deactivate the module from backend menu, the function of forms is normal.

I'm not sure, what you mean with "update your phtml files".

**Comment by Drifti** [comment]
You mean updating these 2 phtml?
app/design/frontend/base/default/template/customer/form/register.phtml
app/design/frontend/base/default/template/contacts/form.phtml
If I chose "Replace template" in your menu, the modified phtml in the extension is used, I think? 
Are these modified phtml ready to use or are changes necessary?
Under the registristraton form is a ReCaptcha seen for 2 seconds, but nothing happens.

**Comment by jacquesbh** [comment]
Yes you are right. Contact and customer registration forms are normally working and good to go.

Do you have a custom theme? Can you tell me which are the templates used for the both forms please?

**Comment by Drifti** [comment]
I'm using the rwd theme. No custom changes.
So it's for contact form:
app/design/frontend/rwd/default/template/contacts/form.phtml ,
but there is no special form in rwd for registration. So base is used.
I verified it's this app/design/frontend/base/default/template/customer/form/register.phtml
