### ISSUE TITLE
Interferes with success message

### ISSUE THREAD

**Issue by posidonius** [monsieurbiz/Mbiz_InvisibleCaptcha#4]
Great extension that works well, except it interferes with the success message so there is no feedback to the user after the message has been sent.

**Comment by jacquesbh** [comment]
Hum, it should not.
We don't touch the flow of sending the message and the success is not touched as well.

Can you give us more details please?

Thanks.

**Comment by posidonius** [comment]
Alright, I double checked and it seem to be OK. I guess it was maybe a cache product with my browser when I was testing it. Sorry for the trouble.

**Comment by jacquesbh** [comment]
No problem. I'm glad it's working well.
